matrix-org/matrix-widget-api

src/AlmostEventEmitter.ts
src/ClientWidgetApi.ts
src/WidgetApi.ts
src/index.ts
src/interfaces/ModalButtonKind.ts
src/interfaces/ModalWidgetActions.ts
src/interfaces/WidgetApiAction.ts
src/interfaces/WidgetConfigAction.ts
src/transport/ITransport.ts

https://github.com/matrix-org/matrix-doc/blob/travis/msc/modal-widgets/proposals/2790-modal-widgets.md

MSC2790 Modal Widgets

---

src/ClientWidgetApi.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/IRoomEvent.ts
src/interfaces/SendEventAction.ts
src/interfaces/WidgetApiAction.ts
src/models/WidgetEventCapability.ts

MSC: https://github.com/matrix-org/matrix-doc/pull/2762
The capabilities introduced by MSC2762 are a bit annoying to parse and handle, so they spawned a utility class in this PR. The utility class just makes the code a bit clearer and easier to follow, at the risk of added complexity.
Documentation is intentionally left for a later PR. Tests would be nice, however none of the widget-api has tests at the moment :(

Add an implementation of MSC2762: send/receive events

---

src/WidgetApi.ts
src/index.ts
src/interfaces/ModalWidgetActions.ts
src/interfaces/SetModalButtonEnabledAction.ts
src/interfaces/WidgetApiAction.ts

MSC: https://github.com/matrix-org/matrix-doc/pull/2790
**Required by https://github.com/matrix-org/matrix-react-sdk/pull/5412**

Support being able to disable modal widget buttons (MSC2790 extension)

---

src/interfaces/ApiVersion.ts

It's not actually a release, so we shouldn't be advertising support for it.

Remove v0.1.0 support from the CurrentApiVersions for now

---

.gitignore
README.md
examples/.gitignore
examples/widget/index.css
examples/widget/index.html
examples/widget/utils.js
package.json
yarn.lock

This currently says to use `0.1.0` which doesn't exist, but the plan is to release soon and not accidentally leave the docs pointing at a random RC.
When combined with enough Element changes to work, the example widget looks like this:

Prepare and demonstrate usage in a browser environment

---

src/ClientWidgetApi.ts
src/WidgetApi.ts
src/interfaces/ApiVersion.ts
src/interfaces/CapabilitiesAction.ts
src/interfaces/WidgetApiAction.ts

This causes the `ready` event of the `WidgetApi` to change to when the client notifies the widget of its approved capabilities (when the client supports the MSC).
MSC2871: https://github.com/matrix-org/matrix-doc/pull/2871

Add support for MSC2871: Notifying the widget of its capabilities

---

src/WidgetApi.ts
src/models/WidgetEventCapability.ts

Updates:
* https://github.com/matrix-org/matrix-doc/pull/2762/commits/8ad19262f68bda1e57e369a0245b618bbc9841a1
* https://github.com/matrix-org/matrix-doc/pull/2762/commits/3aa58ee029f923ecdffe8b307fd328d984881647
In slightly more detail: this introduces the escaping mechanics as well as limiting the parsing to expected event types.

Support the updated parsing of event capabilities in MSC2762

---

examples/widget/index.html

The JS code looks for `userId`, not `user_id`. With the current example the initialisation fails.

Update example: change url param to userId

---

package.json

Moves `@types/events` from devDependencies to dependencies. When a user just installs `matrix-widget-api`, the definitions for the `WidgetApi.on` function will not exist.

Add @types/events to dependencies

---

src/ClientWidgetApi.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/ApiVersion.ts
src/interfaces/NavigateAction.ts
src/interfaces/WidgetApiAction.ts

MSC: https://github.com/matrix-org/matrix-doc/pull/2931
See https://github.com/matrix-org/matrix-react-sdk/pull/5527
This experiments with a new way of handling unstable features from MSCs by using `@deprecated` on the entry points into the system.

Support MSC2931 navigation

---

src/templating/url-template.ts

This renames the URL templating data to make it clear that the room ID is locked
to the room where the widget was added (instead of being the currently viewed
room).
Relates to https://github.com/vector-im/element-web/issues/16337
Used by https://github.com/matrix-org/matrix-react-sdk/pull/5607

Rename room ID to indicate new meaning

---

src/ClientWidgetApi.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/ApiVersion.ts
src/interfaces/ReadEventAction.ts
src/interfaces/WidgetApiAction.ts
src/models/WidgetEventCapability.ts

MSC: https://github.com/matrix-org/matrix-doc/pull/2876
For https://github.com/vector-im/element-web/issues/15747

Support MSC2876: Reading events from rooms

---

src/interfaces/ModalWidgetActions.ts

This is a small change that would allow us to initialize modal widget buttons as disabled.
Related PR: https://github.com/matrix-org/matrix-react-sdk/pull/6178
Signed-off-by: Steffen Kolmer steffen.kolmer@nordeck.net

Allow modal widget buttons to be disabled when the modal opens

---

src/ClientWidgetApi.ts
src/Symbols.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/Capabilities.ts
src/interfaces/ReadEventAction.ts
src/interfaces/SendEventAction.ts

MSC: https://github.com/matrix-org/matrix-doc/pull/2762
Additions: https://github.com/matrix-org/matrix-doc/pull/2762/commits/8eedf1d6c4028a39d8357b63bdaefaae63538dae
Like https://github.com/matrix-org/matrix-widget-api/pull/9, this intentionally has minimal docs and no tests (alongside most of the widget-api). Yay beta.

Add timeline support from MSC2762

---

src/ClientWidgetApi.ts

Fixes: https://github.com/vector-im/element-web/issues/15866
This is a draft for discussion.
The way I understand it is, that the ready event in the WidgetApi is only emitted in the `handleCapabilities` function.
This event is needed for the widget to load.
Reloading the Iframe also needs to emit "ready" in the widgetApi. This can only be achieved by the `WidgetApiToWidgetAction.Capabilities` action. (receiving this action calls the `handleCapabilities` function).
But the only place this action is send is in: `beginCapabilities` of the WidgetClientApi.
So it should not be skipped even if the capabilities are already finished `capabilitiesFinished`. 
I don't see the issue with allowing beginCapabilities to be called again when the "load" event from the I frame is triggered. Am I missing …

Call beginCapabilities again when iframe reloads

---

src/interfaces/Capabilities.ts

This PR fixes vector-im/element-web#20920 by deprecating RequiresClient as it will be moved to ElementWidgetCapabilities.
See also matrix-org/matrix-react-sdk#7935
Signed-off-by: Robin Kouwenhoven <r.kouwenhoven@outlook.com>

Deprecate RequiresClient as it will be moved

---

src/ClientWidgetApi.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/SendToDeviceAction.ts
src/interfaces/WidgetApiAction.ts
src/models/WidgetEventCapability.ts

https://github.com/matrix-org/matrix-spec-proposals/pull/3819

Implement MSC3819: Allowing widgets to send/receive to-device messages

---

src/ClientWidgetApi.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/ApiVersion.ts
src/interfaces/Capabilities.ts
src/interfaces/TurnServerActions.ts
src/interfaces/WidgetApiAction.ts
tsconfig.json

https://github.com/matrix-org/matrix-spec-proposals/pull/3846/

Implement MSC3846: Allowing widgets to access TURN servers

---

README.md

in preparation for v1.0.0. Travis has OK'd the removal of this warning out-of-band.

Remove the stability warning from the README

---

src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/interfaces/SendToDeviceAction.ts

That's what they are in the spec, so might as well make that explicit in the types here.

Specify that to-device messages must be objects

---

src/ClientWidgetApi.ts
test/ClientWidgetApi-test.ts

This is a follow up to #72.
The driver can throw an exception, e.g. when the referenced event doesn't exist or when the user is not authorized to see it due to the configured history visibility rules. Without this change, the call times out because the error is not forwarded via the transport channel.

Catch exceptions from the widget driver in the event relations endpoint

---

src/ClientWidgetApi.ts
src/driver/WidgetDriver.ts
src/interfaces/ReadRelationsAction.ts
test/ClientWidgetApi-test.ts
test/WidgetApi-test.ts

Relates to https://github.com/matrix-org/synapse/issues/12930
This removes the unspecced `original_event` field that will be removed from the Synapse soon. Since this API should work like the `/relations` endpoint of the CS-API, the field shouldn't be included here. I also removed the field from https://github.com/matrix-org/matrix-spec-proposals/pull/3869.

Remove unspecced `original_event` field from the `readEventRelations` response

---

src/WidgetApi.ts
test/WidgetApi-test.ts

This makes the `getClientVersions` function on `WidgetApi` public and tests it. 
It is quite useful that the versions are exchanged between client and widget, so that the widget knows which capabilities the client has. But up to now, a widget can not access these details. We recently add #72 which evolves the API, but for now there is no way to detect whether it is really supported before running into errors. We would prefer to make a check and notify the user that he has to update to a newer Element version.

Make `getClientVersions` public

---

src/ClientWidgetApi.ts
src/models/WidgetEventCapability.ts
test/ClientWidgetApi-test.ts

And add some tests for reading state events while we're at it.
For https://github.com/vector-im/element-web/issues/24858
Regressed by a8fc2b929564fac88d0bf0e6f175c8299190871e

Fix reading state events without a specific state key

---

src/templating/url-template.ts
test/url-template-test.ts

I mentioned the need for this parameter in the related [MSC 3891 ](https://github.com/matrix-org/matrix-spec-proposals/pull/3819) which implements to device messages. They are relying on the device id to be available, but there is currently no way to access a device id from within a widget (Element Call does this but is cheating :P). Therefore [I propose to include the device id in the available parameters](https://github.com/matrix-org/matrix-spec-proposals/pull/3819#discussion_r1099833846).

Extend url template variables with device_id

---

package.json
src/ClientWidgetApi.ts

So the widget fails less silently if waitForIFrameLoad=false is specified but the widget doesn't send the contentLoaded event, to help prevent people like me being daft and wasting ages because they reverted one bit of code and not the other.
Also fixes a couple of typos.

Add a warning if contentLoaded event isn't received

---

src/ClientWidgetApi.ts

Fixes https://github.com/matrix-org/matrix-widget-api/issues/88

Emit error:preparing if we fire preparing but never make it to ready

---

src/ClientWidgetApi.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/ApiVersion.ts
src/interfaces/Capabilities.ts
src/interfaces/GetMediaConfigAction.ts
src/interfaces/UploadFileAction.ts
src/interfaces/WidgetApiAction.ts
src/templating/url-template.ts
test/ClientWidgetApi-test.ts
test/WidgetApi-test.ts
test/url-template-test.ts

See https://github.com/matrix-org/matrix-spec-proposals/pull/4039 for more details.

Implement MSC4039: Add an MSC for a new Widget API action to upload files into the media repository

---

src/ClientWidgetApi.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/Capabilities.ts
src/interfaces/SendEventAction.ts
src/interfaces/UpdateDelayedEventAction.ts
src/interfaces/WidgetApiAction.ts
test/ClientWidgetApi-test.ts
test/WidgetApi-test.ts

This is part of the recent revisions to MSC4140/4157.  ~Another PR will be made for adding a widget capability for using the now-authenticated endpoint for sending/canceling/refreshing a future.~ This PR also includes the widget action & capability for sending/canceling/refreshing a delayed event.
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>

Satisfy revised MSC4157

---

CONTRIBUTING.md

The Matrix.org Foundation is rolling out this DCO across all public repositories in its namespace. Of note, this DCO does not require the use of "real" or "legally identifiable" names.
Signed-off-by: Josh Simmons <git@josh.tel>

remove real name requirement from DCO

---

.eslintrc.js
src/ClientWidgetApi.ts
src/WidgetApi.ts
src/driver/WidgetDriver.ts
src/interfaces/IWidgetApiErrorResponse.ts
src/transport/ITransport.ts
src/transport/PostmessageTransport.ts
test/ClientWidgetApi-test.ts
test/WidgetApi-test.ts

Currently, error responses from CS-API requests are re-thrown/rejected without their HTTP status code or `errcode` string.  This PR passes them along, because otherwise clients that may run either standalone or as a widget cannot reliably use HTTP status codes on error responses, as the latter would not receive them.
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>

Pass HTTP status code & errcode from CS-API errors

---

src/ClientWidgetApi.ts
src/interfaces/ApiVersion.ts
src/interfaces/LanguageChangeAction.ts
src/interfaces/ThemeChangeAction.ts
src/interfaces/WidgetApiAction.ts
test/ClientWidgetApi-test.ts

[MSC2873](https://github.com/matrix-org/matrix-spec-proposals/pull/2873) specifies some actions for updating the widget's theme/language after it's loaded, and I'd like to make use of them.

Expand support for MSC2873 (changing theme/language)

---

src/index.ts

I missed this earlier, and it's breaking CI because one of the files is considered unused.

Export theme and language action types

---

src/ClientWidgetApi.ts
src/driver/WidgetDriver.ts
src/index.ts
src/interfaces/UpdateStateAction.ts
src/interfaces/WidgetApiAction.ts
test/ClientWidgetApi-test.ts

This is an implementation of [an update to MSC2762](https://github.com/matrix-org/matrix-spec-proposals/pull/4237). See the description there for an explainer.

Distinguish room state and timeline events

---

.gitignore
src/ClientWidgetApi.ts
src/interfaces/ApiVersion.ts
test/ClientWidgetApi-test.ts

Required for: https://github.com/matrix-org/matrix-js-sdk/pull/4652 (this pr also provides more background on why this is needed)
Let the client only send UpdateState if the widget supports it.

Add UPDATE_STATE widget api version

---

.github/workflows/blocked.yaml

Adapted from matrix-js-sdk (https://github.com/matrix-org/matrix-js-sdk/blob/develop/.github/workflows/pull_request.yaml)
For https://github.com/element-hq/voip-internal/issues/303

Prevent PRs with the X-Blocked label from being merged
